server:
  port: 8096
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///demo?serverTimezone=UTC
    username: root
    password: root

mybatis:
  typeAliasesPackage: com.oppo.pojo